services:
  logo-api-postgresql:
    image: postgres:15-alpine
    container_name: logo-api-postgres
    environment:
      POSTGRES_DB: logo_db
      POSTGRES_USER: logo_user
      POSTGRES_PASSWORD: logo_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - logo_api_postgres_data:/var/lib/postgresql/data
    networks:
      - logo-api-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logo_user -d logo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  logo-api-adminer:
    image: adminer:4.8.1
    container_name: logo-api-adminer
    ports:
      - "8083:8080"
    environment:
      ADMINER_DEFAULT_SERVER: logo-api-postgresql
      ADMINER_DESIGN: pepa-linha
    networks:
      - logo-api-network
    depends_on:
      logo-api-postgresql:
        condition: service_healthy
    restart: unless-stopped

#  logo-api-app:
#    build: .
#    container_name: logo-api-application
#    ports:
#      - "8082:8082"
#    environment:
#      # Database configuration
#      PGHOST: logo-api-postgresql
#      PGPORT: 5432
#      PGDATABASE: logo_db
#      DATABASE_USERNAME: logo_user
#      DATABASE_PASSWORD: logo_password
#      # Disable dev services when running in Docker
#      DEV_SERVICES_ENABLED: false
#      # Application configuration
#      PORT: 8082
#      QUARKUS_PROFILE: prod
#    networks:
#      - logo-api-network
#    depends_on:
#      logo-api-postgresql:
#        condition: service_healthy
#    restart: unless-stopped

volumes:
  logo_api_postgres_data:

networks:
  logo-api-network:
    driver: bridge
